blank_issues_enabled: true
contact_links:
  - name: Discussions - Q&A / Ideas
    url: https://github.com/mdcanocreates/phytrace/discussions
    about: For open-ended questions, feature brainstorming, or general discussion
